// sample_code/front-end/nuxtjs/news_list.vue
<template>
  <div>
    <p>News list</p>
    <div v-for="n in response.list" :key="n.slug">
      <nuxt-link :to="`/news/${n.topics_id}`">
        {{ n.ymd }} {{ n.subject }}
      </nuxt-link>
    </div>
  </div>
</template>

<script>
export default {
  async asyncData({ $axios }) {
    return {
      response: await $axios.$get('/rcms-api/4/news'),
    };
  },
};
</script>

// sample_code/front-end/nextjs/news_list.jsx
import Link from 'next/link';

async function getData() {
  const res = await fetch(process.env.NEXT_PUBLIC_BASE_URL + '/rcms-api/4/news');
  return res.json()
}

export default async function Page() {
  const data = await getData()
 
  return (
    <div>
      <p>News list</p>
      {data.list.map((n) => (
        <div key={n.slug}>
          <Link href={`/news/${n.topics_id}`}>
            {n.ymd} {n.subject}
          </Link>
        </div>
      ))}
    </div>
  );
}
